POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
    "username": "monkey",
    "password": "hbg19950616"
}

###

POST  http://localhost:3000/article/save HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vbmtleSIsInN1YiI6IjViOGY5NjhkZjgzYjNiMjAzODFjY2YxZCIsImlhdCI6MTU5NDkwNTk5OSwiZXhwIjoxNTk0OTEzMTk5fQ.3PV8kJTcvHU5P4brQT2osR6ng3tOUc6HsOknaRuah_I

###

GET  http://localhost:3000/article/list HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vbmtleSIsInN1YiI6IjViOGY5NjhkZjgzYjNiMjAzODFjY2YxZCIsImlhdCI6MTU5NTE2MTgyOCwiZXhwIjoxNTk1MTY5MDI4fQ.Mk4IIaE0QT9mrnNiFJVJdaLIR6u_7OGUvvTlAckYGFw
content-type: application/json


###
GET  http://localhost:3000/music/list HTTP/1.1
content-type: application/json

###
POST http://localhost:9000/api/hooks/release/builtin/1/54dd239461f256028795b55b9ff845d7b4bea6ed6def86ba30ffee39a154eb11 HTTP/1.1
content-type: application/json

{"version": "abcdefg"}

###
GET http://test-api-bmb.snsports.cn/GetMerchantList HTTP/1.1
#content-type: application/json
